# Generated by Django 2.2.3 on 2019-07-15 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smeApi_auth', '0002_auto_20190714_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2019-07-15 11:17:56.172985+01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        )
    ]
